### PR TITLE
Short tag portal

### PR DESCRIPTION
**Pull request by jpaddison3**

### CODE REVIEW

**Comment by jpaddison3** [comment]
Desktop:
image

**Comment by jpaddison3** [comment]
Mobile:
image

**Comment by jpaddison3** [comment]
The edit button is admin only

**Comment by colophonemes** [comment]
The headings on mobile maybe seem too close to the edge? This feels like it might be something that's generically an issue on the whole site though, so maybe outside the scope of the PR.

**Review by colophonemes — APPROVED** [review]
ASTLAC

**Comment by jpaddison3** [comment]
I could be persuaded that's a problem, but it is indeed not because of this PR.

**Comment by jpaddison3** [comment]
Thx for the quick review

**Pull request merged**
