### PR TITLE
Post default sticky priority migration

### PR DESCRIPTION
**Pull request by jcmustin**
Posts without a set sticky priority get sorted below all other posts on the front page. This affects posts from before ~April 30th of this year. Aaron ran into this while trying to publish an old draft from a forum user, which he couldn't get  to show up on the front page.

This PR resolves this by filling in the default priority for all posts.

### CODE REVIEW

**Review by jpaddison3 — CHANGES_REQUESTED** [review]
You need to import the migration

**Comment by jpaddison3** [comment]
And I would like you to test it on dev before shipping

**Comment by jcmustin** [comment]
Sorry about that, got a bit ahead of myself. I've now tested the migration on dev, and everything looks good to me.

**Review by jpaddison3 — APPROVED** [review]
LGTM

**Pull request merged**
