### PR TITLE
Bring EA Forum up to speed with LessWrong [WIP]

### PR DESCRIPTION
**Pull request by Discordius**
**Major changes introduced in this PR:** 

* Centralized all Meteor functions in one file, in preparation for ripping out Meteor
* Introduction of GatherTown components and /walledGarden Urls
* Ripping out LogRocket
* Infinite Scroll and Multi-Type feeds on the frontpage, integrated with the tagging system
* All collection functions have been moved to their own utility functions, and are no longer monkeypatched on top of the collections (i.e. `Posts.getPageUrl` has become `getPostPageUrl`)
* Upgraded Apollo to version 3.0 and fixed a bunch of issues related to that
* Make it possible to comment on tags, and with that, make commenting mostly collection-agnostic. Also add Tag discussion pages.
* Tag-Revisions with substantial changes now show up in Recent Discussion
* Improved tagging dashboard with flags for which tags need work
* You can now embed Elicit Binary Predictions, Metaculus Predictions and Youtube videos in posts and comments
* CKEditor and Markdown now supports subscript, and superscript

**Changes made so far in the merge:** 

* Upgraded some callbacks to new syntax
* Upgraded a call to newMutation with the new createMutator name
* Commented out GatherTown section in RecommendationsAndCurated
* Run GatherTown cronjob only on LessWrong

**Things you will need to do:** 

* Register an Elicit API key and add it to your database settings
* Run a bunch of migrations related to revisions, tags and post-drafts. See below for the current state of our migrations

image

**Things left to test: **

* I tested most of the above, but it's a bit hard without access to a properly populated DB. So I would definitely do a QA pass of clicking around. The most suspicious parts are definitely everything related to the Elicit Integration, and all the new tagging stuff.

### CODE REVIEW

**Comment by jpaddison3** [comment]
> Multi-Type feeds on the frontpage

What do you mean by this?

**Comment by jpaddison3** [comment]
Either I'm drunk or Elicit is not actually in this PR.

**Comment by Discordius** [comment]
> Multi-Type feeds on the frontpage

I.e. we now have some general feed architecture that we can use to display recently created tags, or recently added tags, or (if you wanted to) recently created users, on the frontpage. It used to be that the frontpage recent discussion section was strictly bound to be posts sorted by when they were last commented on.

> Either I'm drunk or Elicit is not actually in this PR.

OOps, yeah, looks like I merged in the wrong order. Will add it to this PR, but can also omit it, whatever your preference is.

**Comment by jpaddison3** [comment]
Am excited to include

**Comment by Discordius** [comment]
Now includes ElicitBlocks. Do make sure to register an API key and to set the relevant setting before you deploy.

**Review by jpaddison3 — APPROVED** [review]
LGTM

**Comment by jpaddison3** [comment]
@Discordius some of your fixes would be best to apply upstream, no? I think those are pretty important, otherwise the diff grows. And when the diff grows, these merges become much harder.

For example: https://github.com/centre-for-effective-altruism/EAForum/pull/121/commits/3aeed7f264903bf90c17bd6c56e18a5a86a72b50

**Comment by Discordius** [comment]
Yeah, I wasn't sure about the ordering. I will make some PRs into the upstream probably early next week.

**Pull request merged**
