### PR TITLE
Merge lw-devel into ea-dev

### PR DESCRIPTION
**Pull request by jcmustin**
I've locally tested the functionality of the features included in this merge, which includes the PRs in LW2's devel branch from [here](https://github.com/LessWrong2/Lesswrong2/pull/4092) to the present, and everything seems to be working.

### CODE REVIEW

**Comment by jpaddison3** [comment]
I would have included a description of the highest risk changes from LW, to transfer knowledge from your existing investigations to your reviewer, and same him duplicate work. Also (and maybe this is just me) I find that when I write up detailed descriptions it serves as a first round of (self) review, where I notice things I don't like and should fix.

**Comment by jpaddison3** [comment]
> I've checked this locally against every PR in LW2's devel branch from here onward

I don't take your meaning. What do you mean "checked against"?

**Review by jpaddison3 — APPROVED** [review]
LGTM

This seems low-risk

**Comment by jcmustin** [comment]
> I don't take your meaning. What do you mean "checked against"?

Yeah that was weird wording, sorry 😅 Better description:
> I've locally tested the functionality of the features included in this merge, which includes the PRs in LW2's devel branch from [here](https://github.com/LessWrong2/Lesswrong2/pull/4092) to the present, and everything seems to be working.

**Comment by jpaddison3** [comment]
Perfect, that's exactly the thing to do. I realized I have a 'script' I run when doing or reviewing merges that you might be interested in.

```
git log --left-right --graph --cherry-pick --oneline --right-only ea-dev...lw-master | grep "Merge pull request" | sed -E 's|^.*Merge pull request #([0-9]+) from.*$|https://github.com/Lesswrong2/Lesswrong2/pull/\1|' | xargs open
```

It has a big that for some reason shows some issues instead of PRs. Note that it's prolly not windows compatible. sed probably needs different args and open is a mac command that will in this case open the url in the default browser.

**Pull request merged**
